---
name: FabonacciPipeline_Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm test
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with: null
        gh_pages: main
        allure_history: allure-history
        allure_results: build/allure-results
      - name: Publish test report
        if: always()
        with: null
        github_token: $
        publish_branch: main
        publish_dir: allure-history
