# This is a basic workflow to help you get started with Actions

name: FabonacciPipeline_Test

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test

    - name: Allure report
  # You may pin to the exact commit or the version.
  # uses: afiore/action-allure-report@e43ebd6f4f4c74b07b1eb02f042902bbe6786a19
  uses: afiore/action-allure-report@v0.1.0
  with:
    # Allure test result data dir
    results-dir: # default is allure-results
    # Allure report target dir
    report-dir: # default is allure-report
          
       
