---
name: FabonacciPipeline_Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm test
        if: always()
        continue-on-error: true
      - name: JEST Report
        uses: RedaktionsNetzwerk-Deutschland/action-jest-reporter@v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} json-glob:**/jest-output.json
          workdir: env.GITHUB_WORKSPACE
