---
name: FabonacciPipeline_Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm test --logger "trx;LogFileName=test-results.trx" || true
        if: always()
        continue-on-error: true
   
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
         name: Jest Tests Result
         path: "**/test-results.trx"                            
         reporter: dotnet-trx
         fail-on-error: true
      
